### ISSUE TITLE
Unapproved use of textcleaner script

### ISSUE THREAD

**Issue by fmw42** [brian-yang/table-parser-opencv#3]
Hello,

I had an inquiry from one of your table-parser-opencv users with a problem. To my surprise, when I looked into your git page, I see that your code uses my textcleaner, bash unix shell script that calls Imagemagick without my permission. Look carefully at my license at the top of the script.

Please contact me about this at fmw at alink dot net.

If you had previously contacted me, my apologies. However, there is inadequate reference to me an my work in your README file and to my licensing conditions.

Fred W

**Comment by brian-yang** [comment]
Hi Fred,

Apologies for not contacting you sooner. I sent you an email at fmw@alink.net regarding licensing and will update the README to reflect that.

Thank you,
Brian
