### ISSUE TITLE
Image compressed unnecessarily 

### ISSUE THREAD

**Issue by macintoshhelper** [brian-yang/table-parser-opencv#7]
The input is being copied to `target.jpg`, but by doing this, the file is being compressed unnecessarily, adding compression artifacting: https://github.com/brian-yang/table-parser-opencv/blob/master/main.py#L27

Should I open a PR to change it to `target.png`?

**Comment by brian-yang** [comment]
Yes, that would definitely be helpful! I can merge the change in ASAP once the pr's made. Thanks!
